#!/usr/bin/env bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update && brew upgrade
brew tap caskroom/cask
brew tap buo/cask-upgrade
brew tap homebrew/science

# Non Cask

NONCASK=(
	android-sdk
	android-ndk
	zsh-syntax-highlighting
	python3
	ccat
	mitmproxy 
	ssh-copy-id
	tmux
	httpie
	wget
	htop
	ffmpeg
	gifsicle
	cdiff
	tree
	safe-rm
	dropbox-uploader
)

for item in ${NONCASK[*]}; do
	brew install $item
done;


# Cask

CASKS=(
	google-chrome
	visual-studio-code
	transmission
	macdown
)

for item in ${CASKS[*]}; do
	brew cask install $item
done;

# Cleanup
brew cleanup
brew cask cleanup
