#!/usr/bin/env bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update && brew upgrade

# Non Cask
NONCASK=(
    zsh-syntax-highlighting
    mitmproxy
    ssh-copy-id
    tmux
    httpie
    wget
    htop
    gifsicle
    cdiff
    tree
    safe-rm
    tldr
    wd
    git-secret
    go
)

for item in ${NONCASK[*]}; do
    brew install $item
done;


## Cask
## This is now more like a GUI app

CASKS=(
    google-chrome
    visual-studio-code
    transmission
    jetbrains-toolbox
    shiftit
)

for item in ${CASKS[*]}; do
    brew install $item
done;

# Cleanup
brew cleanup
