#!/usr/bin/env bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update && brew upgrade

# Non Cask
NONCASK=(
	zsh-syntax-highlighting
	mitmproxy 
	ssh-copy-id
	tmux
	httpie
	wget
	htop
	gifsicle
	cdiff
	tree
	safe-rm
	dropbox-uploader
	tldr
	wd
)

for item in ${NONCASK[*]}; do
	brew install $item
done;


# Cask

CASKS=(
	google-chrome
	visual-studio-code
	transmission
	jetbrains-toolbox
)

for item in ${CASKS[*]}; do
	brew cask install $item
done;

# Cleanup
brew cleanup
brew cask cleanup
