[[rule]]
toolName = "run_shell_command"
commandPrefix = "rtk git diff"
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
commandPrefix = "rtk ls"
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
commandPrefix = "rtk git status"
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
commandPrefix = "rtk grep"
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
commandPrefix = "rtk find"
decision = "allow"
priority = 100
